variable "tf_env" {}
variable "tags" {}
variable "ami_id" {}
variable "instance_type" {}
variable "public_subnet_id" {}
variable "security_group_ids" {}
variable "key_pair_name" {}
variable "user_data_script" {}
variable "eip_id" {}
variable "required_bastion_setup" {}
